name: Build Printer Helper

on:
  push:
    paths:
      - '**'
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run icons
      - run: npm run dist:unsigned
      - uses: actions/upload-artifact@v4
        with:
          name: mac-artifacts
          path: dist/**

  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run icons
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/**
