name: Release Printer Helper

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run icons
      - run: npm run dist:unsigned
      - uses: actions/upload-artifact@v4
        with:
          name: mac-binaries
          path: dist/**

  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run icons
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: dist/**

  release:
    runs-on: ubuntu-latest
    needs: [build-mac, build-win]
    steps:
      - name: Download mac artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac-binaries
          path: release
      - name: Download windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-binaries
          path: release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Electron Printer Helper ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
